name: Build
on:
  workflow_dispatch:
  # triggers with a push on master
  push:
    branches:
      - 'master'
  # triggers with a pull request into master
  pull_request:
    branches:
      - 'master'
  # triggers with a pull request from steward action
  repository_dispatch:
    branches:
      - 'update/*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "Hello World!"
