name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - '!master'
#      - '*'         # matches every branch that doesn't contain a '/'
#      - '*/*'       # matches every branch containing a single '/'
#      - '**'        # matches every branch
#      - '!master'   # excludes master
  pull_request:
    branches:
      - '**'
env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run tests & Coverage Report
        run: sbt coverage test coverageReport
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: target/scala-2.12/scoverage-report/scoverage.xml
          flags: unittests
          fail_ci_if_error: true
          verbose: true
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/checkout@v2
      - name: Formatting
        run: sbt scalafmtSbtCheck scalafmtCheck test:scalafmtCheck

